### ISSUE TITLE
qualitative analysis code

### ISSUE THREAD

**Issue by Xuehao-Gao** [MiniEval/citl#1]
Hi,
 
 Nice work! Can you share the qualitative analysis code for visualizing the generated human motion (as shown in your Fig.1)?
 
Thx

**Comment by MiniEval** [comment]
Hello,
The visualisations were built in Blender using the output quaternions of our model and the provided LaFAN1 models from https://github.com/ubisoft/ubisoft-laforge-animation-dataset. Provided is the setup used to generate the visualisations.

This repository is a refactored version of the lab code, so the original code does not work directly for bridging the output. You may try build your own. The built-in script in the .blend file takes a space-separated file containing a line of pose data for each frame. The pose data consists of 7 elements (3 position + 4 quaternion) per joint. The position joints are unused for non-root joints.

[extra_vis.zip](https://github.com/MiniEval/citl/files/13446466/extra_vis.zip)
